services:
  # 1. Database Service (PostgreSQL)
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - next-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d test" ]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Next.js Application Service
  next_app:
    build:
      context: .
      target: runner
    container_name: nextjs_app
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/test?schema=public"
    networks:
      - next-network

  # 3. Prisma Studio Service
  prisma-studio:
    image: node:24.15.0-alpine
    container_name: prisma_studio
    working_dir: /app
    volumes:
      - .:/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/test?schema=public"
    networks:
      - next-network
    depends_on:
      database:
        condition: service_healthy

networks:
  next-network:
    name: next-network

volumes:
  postgres_data:
